"""Deterministic graph construction and GraD-Pert view generation."""

from gradpert.graphs.materialization import (
    DatasetGraphLayout,
    load_dataset_graph_topology,
    materialize_dataset_graphs,
    verify_dataset_graphs,
    verify_graph_source_checkout,
)
from gradpert.graphs.pruning import DirectedEdge, PrunedSourceGraph, prune_incoming_edges
from gradpert.graphs.registry import (
    GraphSourceFile,
    GraphSourceRegistry,
    load_graph_source_registry,
)
from gradpert.graphs.views import (
    GraDPertTrainingViews,
    GraphTopology,
    GraphView,
    GraphViewBatch,
    ResolvedLocalViewContract,
    build_fanout_view,
    build_graph_view_batch,
    build_incoming_edge_index,
    build_incoming_neighbor_index,
    build_induced_edge_index,
    build_prediction_graph_view,
    build_ring_induced_view,
    build_training_graph_views,
    clean_graph_view,
    resolve_legacy_local_view_contract,
    resolve_local_view_contract,
    stable_view_seed,
)

__all__ = [
    "DatasetGraphLayout",
    "DirectedEdge",
    "GraDPertTrainingViews",
    "GraphSourceFile",
    "GraphSourceRegistry",
    "GraphTopology",
    "GraphView",
    "GraphViewBatch",
    "PrunedSourceGraph",
    "ResolvedLocalViewContract",
    "build_fanout_view",
    "build_graph_view_batch",
    "build_incoming_edge_index",
    "build_incoming_neighbor_index",
    "build_induced_edge_index",
    "build_prediction_graph_view",
    "build_ring_induced_view",
    "build_training_graph_views",
    "clean_graph_view",
    "load_dataset_graph_topology",
    "load_graph_source_registry",
    "materialize_dataset_graphs",
    "prune_incoming_edges",
    "resolve_legacy_local_view_contract",
    "resolve_local_view_contract",
    "stable_view_seed",
    "verify_dataset_graphs",
    "verify_graph_source_checkout",
]
